gems:            [jekyll-paginate, jekyll-gist]

permalink:       pretty
kramdown:
  input: GFM
  syntax_highlighter: rouge

title:           Oplogo
tagline:         'A personal blog'
description:     'A personal blog tracking my technical exploration.'
url:             https://oplogo.me
enforce_ssl:     oplogo.me
baseurl:         /

author:
  name:          'Yang Yang'
  url:           https://twitter.com/bitdancer

paginate:        5
paginate_path:   'page:num'


github:          'https://github.com/reliveyy'
twitter:         'https://twitter.com/bitdancer'
tumblr:          'https://pointliner.tumblr.com'

timezone:        'Asia/Shanghai'
